sonar.host.url=http://localhost:9000
sonar.projectKey=lms-parent
sonar.projectName=LMS Online Learning System
sonar.projectVersion=1.0.0

sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.java.binaries=**/target/classes
sonar.sources=**/src/main/java
sonar.tests=**/src/test/java