spring:
  application:
    name: payment-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/lms_payment_db?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

razorpay:
  key:
    id: ${RAZORPAY_KEY_ID}
    secret: ${RAZORPAY_KEY_SECRET}

app:
  rabbitmq:
    exchange: lms.events.exchange
    routing-key:
      payment-success: notification.payment.success
      refund: notification.payment.refund

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false
